-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  desc text,
  img text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Objections Table
create table objections (
  id bigint generated by default as identity primary key,
  category text,
  q text not null,
  a text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Tasks Table
create table tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  desc text,
  time text,
  date date,
  done boolean default false,
  user_id uuid, -- Optional if auth is added later
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional for now but good practice
alter table products enable row level security;
alter table objections enable row level security;
alter table tasks enable row level security;

-- Create Policies (Allow Public Read/Write for demo purposes - SECURE THIS LATER)
create policy "Public Access Products" on products for all using (true);
create policy "Public Access Objections" on objections for all using (true);
create policy "Public Access Tasks" on tasks for all using (true);
